### ISSUE TITLE
Got an a problem with the script

### ISSUE THREAD

**Issue by robpanes-space** [coderbyheart/roundcube-webmail-fetcher#1]
@coderbyheart I got this message when trying to pull lists of emails

this.display_message(\"Your session is invalid or expired.\",\"error\",-1000);\nthis.session_error(\".\\\/?_task=login&_err=session\"

Any reason why my session was expired after I login?

Thanks

**Comment by coderbyheart** [comment]
Sorry, I have no idea. This code is 8 years old and it just might be that it no longer works with the current version of RoundCube.
